// The database is the single source of message ordering truth (FOUND-02) --
// messages.id is a monotonic bigserial generated by insert; no
// client-supplied ordering field is ever trusted here. since() is the exact
// shared query behind both SSE Last-Event-ID backfill (Plan 01-08) and the
// D-16 polling fallback endpoint.
//
// This module only persists -- it never calls pg_notify. That happens in
// the write-path route handler (Plan 01-06), in the same transaction as
// the insert, per 01-RESEARCH.md's durability-first Anti-Pattern note.
import { and, asc, eq, gt } from "drizzle-orm";
import { db } from "../db/pool.ts";
import { messages } from "../db/schema.ts";

export type Message = typeof messages.$inferSelect;
export type MessageSender = "visitor" | "owner";

/**
 * Inserts a message and returns the full row (its new id becomes the SSE
 * event id). If `clientMsgId` is given and a row already exists for
 * (conversationId, clientMsgId), returns that existing row instead of
 * inserting a duplicate -- idempotent retry support for D-19.
 *
 * Known limitation: this is a select-then-insert check, not a single
 * atomic statement -- the schema has no unique constraint on
 * (conversation_id, client_msg_id) to arbitrate an ON CONFLICT clause
 * against (adding one is a schema change, out of this plan's scope). Two
 * truly concurrent calls with the same clientMsgId could both pass the
 * check and insert twice. In practice D-19's retries are sequential
 * (client retries only after a prior attempt fails), so this is a low-risk
 * gap, not a correctness hole for the retry pattern it exists to support.
 */
export async function create(
  conversationId: number,
  sender: MessageSender,
  body: string,
  clientMsgId?: string | null,
): Promise<Message> {
  if (clientMsgId) {
    const [existing] = await db
      .select()
      .from(messages)
      .where(and(eq(messages.conversationId, conversationId), eq(messages.clientMsgId, clientMsgId)))
      .limit(1);
    if (existing) return existing;
  }

  const [created] = await db
    .insert(messages)
    .values({ conversationId, sender, body, clientMsgId: clientMsgId ?? null })
    .returning();
  return created;
}

/** All messages for a conversation with id > sinceId, ascending by id. */
export async function since(conversationId: number, sinceId: number): Promise<Message[]> {
  return db
    .select()
    .from(messages)
    .where(and(eq(messages.conversationId, conversationId), gt(messages.id, sinceId)))
    .orderBy(asc(messages.id));
}
