// The database is the single source of message ordering truth (FOUND-02) --
// messages.id is a monotonic bigserial generated by insert; no
// client-supplied ordering field is ever trusted here. since() is the exact
// shared query behind both SSE Last-Event-ID backfill (Plan 01-08) and the
// D-16 polling fallback endpoint.
//
// This module only persists -- it never calls pg_notify. That happens in
// the write-path route handler (Plan 01-06), in the same transaction as
// the insert, per 01-RESEARCH.md's durability-first Anti-Pattern note.
import { and, asc, eq, gt, isNull } from "drizzle-orm";
import { db } from "../db/pool.ts";
import { OWNER_LANG } from "../config/models.ts";
import { messages, messageTranslations } from "../db/schema.ts";

export type Message = typeof messages.$inferSelect;
export type MessageSender = "visitor" | "owner";

// Plan 02-05: since()/sinceAll()'s rows carry this superset shape so every
// existing SSE/polling/SSR consumer (chat/stream/route.ts,
// admin/stream/route.ts, src/app/api/messages/route.ts -- all three forward
// the whole row object as-is) transparently gains each message's OWNER_LANG
// translation with zero changes to those consumer files.
export type MessageWithTranslation = Message & { translation: string | null };

const MESSAGE_COLUMNS = {
  id: messages.id,
  conversationId: messages.conversationId,
  sender: messages.sender,
  body: messages.body,
  clientMsgId: messages.clientMsgId,
  createdAt: messages.createdAt,
  deliveredAt: messages.deliveredAt,
  translation: messageTranslations.translatedText,
} as const;

// Shared LEFT JOIN filtered to OWNER_LANG -- a message with no
// message_translations row for OWNER_LANG (not yet translated, same-language
// skip, or a failed translation) yields `translation: null`, never a
// degenerate row.
function messagesWithOwnerLangTranslation() {
  return db
    .select(MESSAGE_COLUMNS)
    .from(messages)
    .leftJoin(
      messageTranslations,
      and(eq(messageTranslations.messageId, messages.id), eq(messageTranslations.targetLang, OWNER_LANG)),
    );
}

// Structural subset of `db` (also satisfied by a `db.transaction()`
// callback's `tx` argument, since drizzle-orm's PgTransaction extends
// PgDatabase) -- lets create()/markDelivered() run either against the
// shared pool (default) or inside a caller-supplied transaction. Plan
// 01-08's write routes pass their own `tx` so the insert and the
// same-transaction pg_notify call commit or roll back together (CHAT-06's
// durability-first requirement).
type DbExecutor = Pick<typeof db, "select" | "insert" | "update">;

/**
 * Inserts a message and returns the full row (its new id becomes the SSE
 * event id). If `clientMsgId` is given and a row already exists for
 * (conversationId, clientMsgId), returns that existing row instead of
 * inserting a duplicate -- idempotent retry support for D-19.
 *
 * Known limitation: this is a select-then-insert check, not a single
 * atomic statement -- the schema has no unique constraint on
 * (conversation_id, client_msg_id) to arbitrate an ON CONFLICT clause
 * against (adding one is a schema change, out of this plan's scope). Two
 * truly concurrent calls with the same clientMsgId could both pass the
 * check and insert twice. In practice D-19's retries are sequential
 * (client retries only after a prior attempt fails), so this is a low-risk
 * gap, not a correctness hole for the retry pattern it exists to support.
 */
export async function create(
  conversationId: number,
  sender: MessageSender,
  body: string,
  clientMsgId?: string | null,
  executor: DbExecutor = db,
): Promise<Message> {
  if (clientMsgId) {
    const [existing] = await executor
      .select()
      .from(messages)
      .where(and(eq(messages.conversationId, conversationId), eq(messages.clientMsgId, clientMsgId)))
      .limit(1);
    if (existing) return existing;
  }

  const [created] = await executor
    .insert(messages)
    .values({ conversationId, sender, body, clientMsgId: clientMsgId ?? null })
    .returning();
  return created;
}

/** All messages for a conversation with id > sinceId, ascending by id. This
 * is the exact shared query behind both SSE Last-Event-ID backfill (Plan
 * 01-08) and the D-16 polling fallback (GET /api/messages?since=). Plan
 * 02-05: each row also carries `translation: string | null` (the message's
 * OWNER_LANG translation, or null when none exists). */
export async function since(conversationId: number, sinceId: number): Promise<MessageWithTranslation[]> {
  return messagesWithOwnerLangTranslation()
    .where(and(eq(messages.conversationId, conversationId), gt(messages.id, sinceId)))
    .orderBy(asc(messages.id));
}

/** All messages across every conversation with id > sinceId, ascending by
 * id -- the admin firehose's (D-13) own Last-Event-ID backfill, so an
 * owner reconnect never loses a message either. Plan 02-05: each row also
 * carries `translation: string | null` (the message's OWNER_LANG
 * translation, or null when none exists). */
export async function sinceAll(sinceId: number): Promise<MessageWithTranslation[]> {
  return messagesWithOwnerLangTranslation()
    .where(gt(messages.id, sinceId))
    .orderBy(asc(messages.id));
}

/**
 * PUSH-08: sets the durable ACK marker for `messageId`. The `isNull` guard
 * makes a duplicate ack call a harmless no-op rather than repeatedly
 * overwriting the timestamp -- same set-once spirit as gateFunnel.ts's
 * upserts.
 */
export async function markDelivered(messageId: number, executor: DbExecutor = db): Promise<void> {
  await executor
    .update(messages)
    .set({ deliveredAt: new Date() })
    .where(and(eq(messages.id, messageId), isNull(messages.deliveredAt)));
}

/**
 * True if `messageId` belongs to `conversationId`. Used by Plan 02-06's ack
 * endpoint so a visitor can only ack a message inside their own open
 * conversation, never an arbitrary message id.
 */
export async function belongsToConversation(messageId: number, conversationId: number): Promise<boolean> {
  const [row] = await db
    .select({ id: messages.id })
    .from(messages)
    .where(and(eq(messages.id, messageId), eq(messages.conversationId, conversationId)))
    .limit(1);
  return row !== undefined;
}

/**
 * PUSH-08: reads the current `delivered_at` value for `messageId` -- a
 * natural sibling to `markDelivered` above, added in Plan 02-04 for
 * `send.ts`'s grace-period re-check (skip the push send entirely if the
 * visitor's own SSE-receipt ack already landed). Returns `null` both when
 * the message hasn't been acked yet and when `messageId` doesn't exist.
 */
export async function getDeliveredAt(messageId: number): Promise<Date | null> {
  const [row] = await db
    .select({ deliveredAt: messages.deliveredAt })
    .from(messages)
    .where(eq(messages.id, messageId))
    .limit(1);
  return row?.deliveredAt ?? null;
}
